/*
 * PlayOnDlna - An Android application to play media on dlna devices
 * Copyright (C) 2025 Lukas Scheerer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package io.github.scovillo.playondlna.preparation

import android.util.Log
import androidx.compose.runtime.State
import androidx.compose.runtime.mutableStateOf
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.arthenica.ffmpegkit.FFmpegKit
import com.arthenica.ffmpegkit.ReturnCode
import com.arthenica.ffmpegkit.Session
import io.github.scovillo.playondlna.R
import io.github.scovillo.playondlna.download.HttpStatusException
import io.github.scovillo.playondlna.download.PlayOnDlnaStreamDownload
import io.github.scovillo.playondlna.download.PlayOnDlnaVideoInput
import io.github.scovillo.playondlna.download.okHttpClient
import io.github.scovillo.playondlna.model.LibraryItem
import io.github.scovillo.playondlna.model.LibraryMetadata
import io.github.scovillo.playondlna.model.VideoQuality
import io.github.scovillo.playondlna.persistence.LibraryManager
import io.github.scovillo.playondlna.persistence.PlaylistManager
import io.github.scovillo.playondlna.persistence.SettingsRepository
import io.github.scovillo.playondlna.preparation.selection.AudioStreamSelection
import io.github.scovillo.playondlna.preparation.selection.VideoStreamSelection
import io.github.scovillo.playondlna.preparation.selection.bestThumbnailUrl
import io.github.scovillo.playondlna.preparation.selection.hasBestCompatibility
import io.github.scovillo.playondlna.preparation.selection.isMp3Ready
import io.github.scovillo.playondlna.server.mediaFileHttpServer
import io.github.scovillo.playondlna.ui.ToastEvent
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.coroutines.withContext
import okhttp3.Request
import org.schabi.newpipe.extractor.ListExtractor
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.Page
import org.schabi.newpipe.extractor.StreamingService
import org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException
import org.schabi.newpipe.extractor.playlist.PlaylistInfo
import org.schabi.newpipe.extractor.stream.DeliveryMethod
import org.schabi.newpipe.extractor.stream.StreamExtractor
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import org.schabi.newpipe.extractor.stream.VideoStream
import java.io.File
import java.io.IOException
import java.net.URI
import java.security.MessageDigest
import java.util.Collections
import java.util.Locale
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
import kotlin.time.Duration.Companion.milliseconds

enum class MediaFileJobStatus { IDLE, PREPARING, FINALIZING, READY, ERROR }

data class PlaylistPosition(val current: Int, val total: Int)

data class PlaylistImportSummary(val addedEntries: Int, val skippedEntries: Int)

private class DownloadFailedException(cause: Throwable) : Exception(cause)

val VideoStream.hasBestCompatibility: Boolean
    get() {
        return format?.mimeType?.startsWith("video/mp4") == true && codec?.startsWith(
            "avc",
        ) == true
    }

fun StreamExtractor.safeId(): String {
    if (id.matches(Regex("[A-Za-z0-9._-]+"))) return id
    val digest = MessageDigest.getInstance("SHA-256").digest(id.toByteArray())
    return "media_" + digest.take(16).joinToString("") { "%02x".format(it) }
}

fun StreamExtractor.subtitle(): SubtitlesStream? {
    val locale = Locale.getDefault()
    val subtitlesM4a = getSubtitles(MediaFormat.SRT)
    Log.i(
        "[M4A]Subtitles",
        subtitlesM4a.joinToString(System.lineSeparator()) {
            "${it.displayLanguageName}, ${it.languageTag}, ${it.format?.mimeType}, ${it.locale}, ${it.isAutoGenerated}"
        },
    )
    return subtitlesM4a.find { it.languageTag.startsWith(locale.language) }
        ?: subtitlesM4a.find { it.languageTag.startsWith("en") }
}

class VideoJobModel(
    settingsRepository: SettingsRepository,
    private val wifiConnectionState: WifiConnectionState,
    private val cacheDir: File,
    private val libraryManager: LibraryManager,
    private val playlistManager: PlaylistManager,
) : ViewModel() {
    private val youtubeUrl = YoutubeUrl()
    private var _currentVideoFile = mutableStateOf<LibraryItem?>(null)
    private var _currentThumbnailFile = mutableStateOf<File?>(null)
    private var _currentFfmpegSession = mutableStateOf<Session?>(null)
    private val _title = mutableStateOf("idle")
    private val _playlistPosition = mutableStateOf<PlaylistPosition?>(null)
    private val _playlistImportSummary = mutableStateOf<PlaylistImportSummary?>(null)
    private val _toastEvents = MutableSharedFlow<ToastEvent>()
    private val _completedSessions = MutableSharedFlow<Long>()
    private val _playbackStarted = MutableSharedFlow<Unit>()
    private val state = MediaFileJobState()

    private val videoQuality: StateFlow<VideoQuality> =
        settingsRepository.videoQualityFlow
            .stateIn(
                scope = viewModelScope,
                started = SharingStarted.Eagerly,
                initialValue = VideoQuality.P720,
            )
    private val isSubtitleEnabled: StateFlow<Boolean> =
        settingsRepository.isSubtitleEnabledFlow
            .stateIn(
                scope = viewModelScope,
                started = SharingStarted.Eagerly,
                initialValue = false,
            )
    private val isInternalSubtitleEnabled: StateFlow<Boolean> =
        settingsRepository.isInternalSubtitleEnabledFlow
            .stateIn(
                scope = viewModelScope,
                started = SharingStarted.Eagerly,
                initialValue = false,
            )
    private val isWlanProtectionEnabled: StateFlow<Boolean> =
        settingsRepository.isWlanProtectionEnabledFlow
            .stateIn(
                scope = viewModelScope,
                started = SharingStarted.Eagerly,
                initialValue = true,
            )
    private val runningJobs = Collections.synchronizedList(mutableListOf<Job>())

    val currentVideoFile: State<LibraryItem?> get() = _currentVideoFile
    val currentThumbnailFile: State<File?> get() = _currentThumbnailFile
    val currentFfmpegSession: State<Session?> get() = _currentFfmpegSession
    val title: State<String> get() = _title
    val playlistPosition: State<PlaylistPosition?> get() = _playlistPosition
    val playlistImportSummary: State<PlaylistImportSummary?> get() = _playlistImportSummary
    val progress: State<Float> get() = state.progress
    val status: State<MediaFileJobStatus> get() = state.status
    val toastEvents = _toastEvents.asSharedFlow()
    val completedSessions = _completedSessions.asSharedFlow()
    val playbackStarted = _playbackStarted.asSharedFlow()

    init {
        this.monitorWifiConnection()
    }

    fun dismissPlaylistImportSummary() {
        _playlistImportSummary.value = null
    }

    fun selectMediaItem(mediaId: String) {
        val item = libraryManager.fetchOneItem(mediaId)
        selectMediaItem(item)
    }

    fun selectMediaItem(item: LibraryItem) {
        mediaFileHttpServer.allFiles[item.metadata.id] = item
        _currentVideoFile.value = item
        state.ready()
    }

    fun selectPlaylist(items: List<LibraryItem>) {
        _currentThumbnailFile.value = items.firstOrNull()?.thumbnail
        items.forEach { item ->
            mediaFileHttpServer.allFiles[item.metadata.id] = item
        }
        viewModelScope.launch {
            _playbackStarted.emit(Unit)
        }
    }

    fun cancelJobs() {
        Log.w("VideoJobModel", "Cancelling ${runningJobs.size} running jobs")
        runningJobs.forEach { it.cancel() }
        runningJobs.clear()
    }

    fun prepareVideo(url: String) {
        val normalizedUrl = youtubeUrl.normalize(url)
        val job =
            viewModelScope.launch(Dispatchers.IO) {
                try {
                    _playbackStarted.emit(Unit)
                    Log.i("VideoJobModel", "Requesting: $normalizedUrl")
                    _currentVideoFile.value = null
                    _currentThumbnailFile.value = null
                    _currentFfmpegSession.value = null
                    _title.value = normalizedUrl
                    val resolvedUrl = resolveSoundCloudShortUrl(normalizedUrl)
                    val service = NewPipe.getServiceByUrl(resolvedUrl)
                    if (service.getLinkTypeByUrl(resolvedUrl) == StreamingService.LinkType.PLAYLIST) {
                        prepareRemotePlaylist(service, resolvedUrl)
                    } else {
                        prepareSingleVideo(resolvedUrl)
                    }
                    if (state.status.value != MediaFileJobStatus.ERROR) {
                        _title.value = "idle"
                        state.idle()
                    }
                    Log.d("VideoJobModel", "Job for $normalizedUrl completed successfully")
                } catch (e: CancellationException) {
                    throw e
                } catch (e: HttpStatusException) {
                    Log.e("VideoJobModel", "HTTP ${e.statusCode} for $normalizedUrl", e)
                    _toastEvents.emit(
                        if (e.statusCode == 401 || e.statusCode == 403) {
                            ToastEvent.Show(R.string.error_video_requires_authentication)
                        } else {
                            ToastEvent.Show(R.string.error_processing_link)
                        },
                    )
                    resetDownloadPanel()
                } catch (e: ContentNotAvailableException) {
                    Log.e("VideoJobModel", "Content unavailable for $normalizedUrl", e)
                    _toastEvents.emit(ToastEvent.Show(R.string.error_processing_link))
                    resetDownloadPanel()
                } catch (e: DownloadFailedException) {
                    Log.e("VideoJobModel", "Download failed for $normalizedUrl", e)
                    _toastEvents.emit(ToastEvent.Show(R.string.download_failed))
                    resetDownloadPanel()
                } catch (e: Exception) {
                    Log.e("VideoJobModel", "Error in job for $normalizedUrl", e)
                    _toastEvents.emit(ToastEvent.Show(R.string.error_processing_link))
                    resetDownloadPanel()
                }
            }
        job.invokeOnCompletion { cause ->
            runningJobs.remove(job)
            when {
                cause is CancellationException -> Log.w("VideoJobModel", "Job for $normalizedUrl was cancelled")
                cause != null -> Log.e("VideoJobModel", "Job for $normalizedUrl failed", cause)
            }
        }
        runningJobs.add(job)
    }

    private suspend fun prepareRemotePlaylist(
        service: StreamingService,
        playlistUrl: String,
    ) {
        val playlistInfo = PlaylistInfo.getInfo(service, playlistUrl)
        val entries = playlistInfo.relatedItems.toMutableList()
        var nextPage: Page? = playlistInfo.nextPage
        while (Page.isValid(nextPage)) {
            val page: ListExtractor.InfoItemsPage<org.schabi.newpipe.extractor.stream.StreamInfoItem> =
                PlaylistInfo.getMoreItems(service, playlistUrl, nextPage!!)
            entries += page.items
            nextPage = page.nextPage
        }
        val playlist =
            playlistManager.createPlaylist(playlistInfo.name)
                ?: throw IllegalStateException("Could not create playlist")
        var addedEntries = 0
        var skippedEntries = 0
        try {
            entries.forEachIndexed { index, entry ->
                _playlistPosition.value = PlaylistPosition(index + 1, entries.size)
                try {
                    val entryUrl = normalizePlaylistEntryUrl(entry.url)
                    check(playlistManager.addVideo(playlist.id, prepareSingleVideo(entryUrl))) {
                        "Could not add playlist entry"
                    }
                    addedEntries++
                } catch (error: CancellationException) {
                    throw error
                } catch (error: DownloadFailedException) {
                    Log.e("VideoJobModel", "Download failed for playlist entry ${entry.url}", error)
                    skippedEntries++
                } catch (error: Exception) {
                    Log.e("VideoJobModel", "Could not prepare playlist entry ${entry.url}", error)
                    skippedEntries++
                }
            }
        } finally {
            _playlistPosition.value = null
        }
        _playlistImportSummary.value = PlaylistImportSummary(addedEntries, skippedEntries)
    }

    private suspend fun mux(
        extractor: StreamExtractor,
        mediaId: String,
    ) {
        if (!isWlanProtectionEnabled.value || wifiConnectionState.isConnected()) {
            state.preparing()
        } else {
            state.error()
            return
        }
        val bestVideo =
            VideoStreamSelection(
                extractor.videoStreams + extractor.videoOnlyStreams,
                videoQuality.value,
            ).best()
        val bestAudio = AudioStreamSelection(extractor.audioStreams).best()
        check(bestVideo != null || bestAudio != null) { "No playable video or audio stream found" }
        val subtitle = if (isSubtitleEnabled.value) extractor.subtitle() else null
        val download =
            PlayOnDlnaStreamDownload(
                mediaId,
                bestVideo?.content,
                cacheDir,
                state,
            )
        val remoteAudioUrl = bestAudio?.takeUnless { it.deliveryMethod == DeliveryMethod.PROGRESSIVE_HTTP }?.content
        if (bestAudio?.deliveryMethod == DeliveryMethod.PROGRESSIVE_HTTP) {
            download.withAudioStream(bestAudio.content)
        }
        if (bestVideo != null && subtitle != null) {
            download.withSubtitle(subtitle)
        }
        val streamFiles =
            try {
                download.start()
            } catch (error: CancellationException) {
                throw error
            } catch (error: Exception) {
                throw DownloadFailedException(error)
            }
        if (bestVideo == null && bestAudio?.isMp3Ready == true && streamFiles.audioFile != null) {
            val libraryItem = createMp3LibraryItem(extractor, mediaId, streamFiles)
            mediaFileHttpServer.allFiles[mediaId] = libraryItem
            _currentVideoFile.value = libraryItem
            state.ready()
            return
        }
        val mediaFile = withContext(Dispatchers.IO) {
            val file = File(cacheDir, "${mediaId}_muxed_final${if (bestVideo == null) ".m4a" else ".mp4"}")
            file.createNewFile()
            file
        }
        val mediaCover = extractor.thumbnails.bestThumbnailUrl()?.let { libraryManager.downloadThumbnail(mediaId, it) }
        val ffmpegCmd =
            PlayOnDlnaFfmpegCommand(
                streamFiles,
                bestAudio?.hasBestCompatibility ?: true,
                mediaFile,
                isInternalSubtitleEnabled.value,
                remoteAudioUrl = remoteAudioUrl,
            )
        Log.i("VideoJobModel", "Final FFMPEGKit command: ${ffmpegCmd.value()}")
        state.finalizing()
        suspendCancellableCoroutine { continuation ->
            _currentFfmpegSession.value =
                FFmpegKit.executeAsync(
                    ffmpegCmd.value(),
                    { session ->
                        if (ReturnCode.isSuccess(session.returnCode)) {
                            Log.d("Mux", "Muxing completed successfully")
                            val libraryItem = LibraryItem(
                                LibraryMetadata(
                                    id = mediaId,
                                    title = extractor.name,
                                    uploader = extractor.uploaderName,
                                    durationInSeconds = extractor.length,
                                    qualityName = if (bestVideo == null) "Audio" else "${bestVideo.height}p",
                                    isAudioOnly = bestVideo == null,
                                ),
                                mediaFile,
                                mediaCover,
                                if (bestVideo == null) null else streamFiles.subtitle,
                            )
                            libraryManager.save(libraryItem.metadata)
                            if (_currentFfmpegSession.value?.sessionId == session.sessionId) {
                                mediaFileHttpServer.allFiles[mediaId] = libraryItem
                                _currentVideoFile.value = libraryItem
                                state.ready()
                                if (continuation.isActive) continuation.resume(Unit)
                            } else if (continuation.isActive) {
                                continuation.resumeWithException(CancellationException("Superseded FFmpeg session"))
                            }
                        } else {
                            Log.e("Mux", "Muxing failed!")
                            state.error()
                            mediaFile.delete()
                            if (continuation.isActive) continuation.resumeWithException(IllegalStateException("Muxing failed"))
                        }
                        streamFiles.delete()
                        viewModelScope.launch { _completedSessions.emit(session.sessionId) }
                    },
                    { log -> Log.d("Mux", log.message) },
                    { statistics ->
                        val videoDurationInMs = extractor.length * 1000
                        val rawProgress =
                            if (videoDurationInMs > 0) (statistics.time * 100 / videoDurationInMs).toFloat() else 0.0f
                        state.updateFinalizingProgress(rawProgress)
                        Log.d("FFmpegProgress", "Progress: $rawProgress%")
                    },
                )
        }
    }

    private suspend fun createMp3LibraryItem(
        extractor: StreamExtractor,
        mediaId: String,
        streamFiles: PlayOnDlnaVideoInput,
    ): LibraryItem {
        state.finalizing()
        val source = requireNotNull(streamFiles.audioFile)
        val mediaFile =
            withContext(Dispatchers.IO) {
                val output = File(cacheDir, "${mediaId}_audio_final_.mp3")
                output.createNewFile()
                source.copyTo(output, overwrite = true)
            }
        val cover = extractor.thumbnails.bestThumbnailUrl()?.let { libraryManager.downloadThumbnail(mediaId, it) }
        val libraryItem = LibraryItem(
            LibraryMetadata(
                id = mediaId,
                title = extractor.name,
                uploader = extractor.uploaderName,
                durationInSeconds = extractor.length,
                qualityName = "Audio",
                isAudioOnly = true,
            ),
            mediaFile,
            cover,
            null
        )
        libraryManager.save(libraryItem.metadata)
        return libraryItem
    }

    private fun resolveSoundCloudShortUrl(url: String): String {
        if (runCatching { URI(url).host }.getOrNull() != "on.soundcloud.com") return url
        return try {
            okHttpClient.newCall(Request.Builder().url(url).head().build()).execute().use { response ->
                response.request.url.toString().also { resolvedUrl ->
                    Log.i("VideoJobModel", "Resolved SoundCloud share URL to $resolvedUrl")
                }
            }
        } catch (error: IOException) {
            Log.w("VideoJobModel", "Could not resolve SoundCloud share URL, using original URL", error)
            url
        }
    }

    private suspend fun prepareSingleVideo(url: String): String {
        val extractor = NewPipe.getServiceByUrl(url).getStreamExtractor(url)
        extractor.fetchPage()
        val mediaId = extractor.safeId()
        _title.value = extractor.name
        if (libraryManager.isExisting(mediaId)) {
            selectMediaItem(mediaId)
        } else {
            mux(extractor, mediaId)
        }
        return mediaId
    }

    private fun resetDownloadPanel() {
        _title.value = "idle"
        state.idle()
    }

    private fun monitorWifiConnection() {
        viewModelScope.launch(Dispatchers.IO) {
            while (isActive) {
                delay(1000.milliseconds)
                if (runningJobs.isEmpty()) {
                    continue
                }
                if (isWlanProtectionEnabled.value && !wifiConnectionState.isConnected()) {
                    withContext(Dispatchers.Main) {
                        _toastEvents.emit(ToastEvent.Show(R.string.wlan_disconnected))
                        state.error()
                    }
                    cancelJobs()
                }
            }
        }
    }
}

internal fun normalizePlaylistEntryUrl(url: String): String = url.replace(Regex("(?<!:)/{2,}"), "/")
